FROM fusuf/whatsasena:latest

RUN git clone https://github.com/amalachuzz/Achutty_v2 /root/WhatsAsenaDuplicated
WORKDIR /root/WhatsAsenaDuplicated/
ENV TZ=Asia/Kolkata
RUN npm install supervisor -g
RUN yarn install --no-audit
RUN git clone https://github.com/amalachuzz/files

CMD ["node", "bot.js"]
